name = "tg-rss-worker"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
TELEGRAM_ADMIN_IDS = "1328163046,-1002559558975,-1002234161183"
MULTIUSER = "false"
DEFAULT_INTERVAL = "5"
MINIMAL_INTERVAL = "5"
USER_SUB_LIMIT = "-1"
CHANNEL_SUB_LIMIT = "-1"
IMG_RELAY_SERVER = "https://rsstt-img-relay.rongrong.workers.dev/"
IMAGES_WESERV_NL = "https://wsrv.nl/"

[[d1_databases]]
binding = "DB"
database_name = "TgRss-D1"
database_id = "b1e6fd90-0a2c-4822-a43b-92dbc763680d"

[[kv_namespaces]]
binding = "KV"
id = "9433416d26fc44ed8cbb232b49325945"

[triggers]
crons = ["*/5 * * * *"]
