name = "lazy-rss"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
TELEGRAM_ADMIN_IDS = "7857830221,-5013019682"
MULTIUSER = "false"
DEFAULT_INTERVAL = "5"
MINIMAL_INTERVAL = "5"
USER_SUB_LIMIT = "-1"
CHANNEL_SUB_LIMIT = "-1"
IMG_RELAY_SERVER = "https://rsstt-img-relay.rongrong.workers.dev/"
IMAGES_WESERV_NL = "https://wsrv.nl/"

[[d1_databases]]
binding = "DB"
database_name = "lazy-d1"
database_id = "edf7b298-7c36-43e5-90bf-53f275d878f2"

[[kv_namespaces]]
binding = "KV"
id = "e8448f88b40343ee928cd8fe52ba04e2"

[triggers]
crons = ["*/5 * * * *"]
